// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package core

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, email, password, user_type, created_at) VALUES(?, ?, ?, ?, NOW())
`

type CreateUserParams struct {
	Name     sql.NullString
	Email    sql.NullString
	Password sql.NullString
	UserType NullUsersUserType
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.UserType,
	)
	return err
}

const deleteMarkedUsers = `-- name: DeleteMarkedUsers :exec
DELETE FROM users
WHERE 
  is_deleted = true AND
  deleted_at > ?
`

func (q *Queries) DeleteMarkedUsers(ctx context.Context, deletedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteMarkedUsers, deletedAt)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, password, user_type, is_banned, is_deleted, deleted_at, created_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.UserType,
			&i.IsBanned,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, user_type, is_banned, is_deleted, deleted_at, created_at FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.IsBanned,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, password, user_type, is_banned, is_deleted, deleted_at, created_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.UserType,
		&i.IsBanned,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, email, password, user_type, is_banned, is_deleted, deleted_at, created_at FROM users
WHERE 
(? is NULL OR user_type = ?) AND
(? is NULL OR is_banned = ?) AND
(? is NULL OR is_deleted = ?)
`

type GetUsersParams struct {
	UserType  NullUsersUserType
	IsBanned  sql.NullBool
	IsDeleted sql.NullBool
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers,
		arg.UserType,
		arg.UserType,
		arg.IsBanned,
		arg.IsBanned,
		arg.IsDeleted,
		arg.IsDeleted,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.UserType,
			&i.IsBanned,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBanState = `-- name: SetBanState :exec
UPDATE users
SET is_banned = ?
WHERE id = ?
`

type SetBanStateParams struct {
	IsBanned sql.NullBool
	ID       int64
}

func (q *Queries) SetBanState(ctx context.Context, arg SetBanStateParams) error {
	_, err := q.db.ExecContext(ctx, setBanState, arg.IsBanned, arg.ID)
	return err
}

const setDeleteState = `-- name: SetDeleteState :exec
UPDATE users
SET is_deleted = ?
WHERE id = ?
`

type SetDeleteStateParams struct {
	IsDeleted sql.NullBool
	ID        int64
}

func (q *Queries) SetDeleteState(ctx context.Context, arg SetDeleteStateParams) error {
	_, err := q.db.ExecContext(ctx, setDeleteState, arg.IsDeleted, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET 
  name = ?,
  email = ?
WHERE
  id = ?
`

type UpdateUserParams struct {
	Name  sql.NullString
	Email sql.NullString
	ID    int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	return err
}
